language: python
dist: xenial
sudo: false

addons:
    postgresql: "9.6"

python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.7-dev" # 3.7 development branch
  - "3.8-dev" # 3.8 development branch
  - "nightly"


env:
  global:
    - ANYBLOK_DATABASE_NAME=travis_ci_test
    - ANYBLOK_DATABASE_DRIVER=postgresql
  matrix:
    - ANYBLOK_DATABASE_USER=postgres

matrix:
  include:
      - python: "pypy3.5"
        env: ANYBLOK_DATABASE_DRIVER=postgresql+psycopg2cffi
        addons:
            postgresql: "9.6"
      - python: "pypy3.5"
        env: ANYBLOK_DATABASE_DRIVER=postgresql+psycopg2cffi
        addons:
            postgresql: "10"
      - python: "3.4"
        addons:
            postgresql: "10"
      - python: "3.5"
        addons:
            postgresql: "10"
      - python: "3.6"
        addons:
            postgresql: "10"
      - python: "3.7"
        addons:
            postgresql: "10"
      
  allow_failures:
      - python: "nightly"
      - python: "pypy3.5"

virtualenv:
  system_site_packages: false

services:
  - postgresql

install:
  - pip install wheel
  - pip install flake8
  - pip install coveralls
  - pip install -U pytest pytest-cov
  - if [[ $TRAVIS_PYTHON_VERSION == 'pypy3.5' ]]; then pip install psycopg2cffi; else pip install psycopg2-binary fi
  - pip install .

script:
  - flake8 anyblok_postgres
  - psql -c 'create database travis_ci_test;' -U postgres
  - py.test --cov-report= --cov=anyblok_postgres anyblok_postgres/tests
  
after_success:
  coveralls --data_file=.coverage --config_file=.coveragerc
